/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#00564a",
        "on-surface": "#dee1f7",
        "border-muted": "#2A3A4E",
        "error-container": "#93000a",
        "inverse-surface": "#dee1f7",
        "primary-fixed-dim": "#26dec2",
        "surface-container": "#1a1f2f",
        "text-primary": "#F0EDE6",
        "surface-bright": "#343949",
        "surface-container-high": "#25293a",
        "inverse-primary": "#006b5c",
        "on-primary": "#00382f",
        "surface-tint": "#26dec2",
        "secondary-container": "#dc9100",
        "on-error-container": "#ffdad6",
        "surface-variant": "#2f3445",
        "inverse-on-surface": "#2b3040",
        primary: "#46f1d3",
        tertiary: "#ffd0a7",
        "secondary-fixed": "#ffddb4",
        "surface-container-highest": "#2f3445",
        "on-secondary": "#452b00",
        "primary-fixed": "#55fbde",
        "surface-container-lowest": "#090e1c",
        "text-secondary": "#94A3B8",
        secondary: "#ffb955",
        "surface-container-low": "#161b2b",
        outline: "#84948f",
        "tertiary-container": "#ffaa55",
        error: "#ffb4ab",
        "on-tertiary": "#4b2800",
        "on-error": "#690005",
        "on-tertiary-container": "#723f00",
        "outline-variant": "#3b4a46",
        "on-primary-fixed": "#00201b",
        "primary-container": "#00d4b8",
        "surface-dim": "#0e1322",
        "secondary-fixed-dim": "#ffb955",
        "on-secondary-fixed": "#291800",
        "on-background": "#dee1f7",
        surface: "#1E2A3B",
        background: "#0e1322",
        "tertiary-fixed-dim": "#ffb875",
        "tertiary-fixed": "#ffdcc0",
        "on-surface-variant": "#bacac5",
        "on-secondary-container": "#4f3100",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
        display: ["Clash Display", "sans-serif"],
        "body-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "body-sm": ["DM Sans"],
        "headline-lg": ["Clash Display"],
        "headline-md": ["Clash Display"],
        "headline-sm": ["Clash Display"],
        "label-md": ["DM Sans"],
        "mono-label": ["DM Sans"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-label": ["12px", { lineHeight: "1", letterSpacing: "0", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
